ARG BASE_IMAGE=nvcr.io/nvidia/l4t-jetpack:r35.3.1
FROM ${BASE_IMAGE}
ARG ROS_DISTRO=humble
WORKDIR /opt/ros/${ROS_DISTRO}
RUN . install/setup.sh && rosinstall_generator --deps --rosdistro ${ROS_DISTRO} robot_localization --exclude RPP \
    > robot_localization.rosinstall
RUN mkdir src && vcs import src < robot_localization.rosinstall
RUN . install/setup.sh && rosdep install -y -r --ignore-src --from-paths src --rosdistro ${ROS_DISTRO}
RUN . install/setup.sh && colcon build --merge-install --cmake-args -DCMAKE_BUILD_TYPE=RelWithDebInfo
RUN rm -rf src build log robot_localization.rosinstall && apt-get clean