ARG BASE_IMAGE=nvcr.io/nvidia/l4t-jetpack:r35.3.1
FROM ${BASE_IMAGE}
ARG ROS_DISTRO=humble
WORKDIR /opt/ros/${ROS_DISTRO}
RUN mkdir src
RUN cd src && git clone https://github.com/RobotWebTools/rosbridge_suite.git
RUN pip3 install tornado twisted autobahn pymongo
RUN . install/setup.sh && colcon build --merge-install
RUN rm -rf build src log