ARG BASE_IMAGE=nvcr.io/nvidia/l4t-jetpack:r35.3.1
FROM ${BASE_IMAGE}
ARG ROS_DISTRO=humble
WORKDIR /opt/ros/${ROS_DISTRO}
RUN . install/setup.sh && ROS_PACKAGE_PATH=/opt/ros/${ROS_DISTRO} rosinstall_generator --deps --rosdistro ${ROS_DISTRO} usb_cam --exclude RPP \
    > usb_cam.rosinstall
RUN mkdir src && vcs import src < usb_cam.rosinstall
RUN . install/setup.sh && rosdep install -y -r --ignore-src --from-paths src --rosdistro ${ROS_DISTRO}
RUN . install/setup.sh && colcon build --merge-install --cmake-args -DCMAKE_BUILD_TYPE=RelWithDebInfo
RUN rm -rf src build log usb_cam.rosinstall && apt-get clean