ARG BASE_IMAGE=nvidia/cuda:12.2.0-devel-ubuntu20.04
FROM ${BASE_IMAGE}
RUN apt update
RUN apt -y install build-essential locales python3
RUN apt install gnupg
RUN apt-key adv --fetch-key https://repo.download.nvidia.com/jetson/jetson-ota-public.asc
RUN add-apt-repository 'deb https://repo.download.nvidia.com/jetson/x86_64/focal r35.2 main'