ARG BASE_IMAGE=nvcr.io/nvidia/l4t-jetpack:r35.3.1
FROM ${BASE_IMAGE}
ARG ROS_DISTRO=humble
WORKDIR /opt/ros/${ROS_DISTRO}
RUN mkdir src
RUN cd src && git clone https://github.com/ros-planning/moveit2.git -b ${ROS_DISTRO}
RUN for repo in moveit2/moveit2.repos $(f="moveit2/moveit2_$ROS_DISTRO.repos"; test -r src/$f && echo src/$f); do vcs import src < "$repo"; done
RUN rosdep install -r --from-paths . --ignore-src --rosdistro $ROS_DISTRO -y
RUN source /opt/ros/${ROS_DISTRO}/install/setup.bash && colcon build --merge-install --cmake-args -DCMAKE_BUILD_TYPE=Release
RUN rm -rf src build log